<?php

namespace Tests\Feature;

use App\Models\Estudiante;
use App\Models\Rol;
use App\Models\User;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class EstudianteCuentaTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(ValidateCsrfToken::class);
    }

    private function createAdmin(): User
    {
        $rol = Rol::create(['nombre_rol' => 'administrador']);

        return User::create([
            'id_rol' => $rol->id_rol,
            'name' => 'Tester',
            'username' => 'tester',
            'email' => 'tester@example.com',
            'password' => Hash::make('password'),
        ]);
    }

    public function test_store_creates_estudiante_with_autogenerated_qr_and_linked_account(): void
    {
        $admin = $this->createAdmin();

        $response = $this->actingAs($admin)->post('/estudiantes', [
            'codigo_universitario' => '201809372',
            'documento_identidad' => '1111111',
            'nombres' => 'Ana',
            'apellidos' => 'Perez',
            'email' => '201809372@est.umss.edu',
        ]);

        $response->assertRedirect(route('estudiantes.index'));
        $response->assertSessionHas('success');

        $this->assertDatabaseHas('estudiante', [
            'codigo_universitario' => '201809372',
            'email' => '201809372@est.umss.edu',
            'codigo_qr' => Estudiante::qrPayload('201809372'),
        ]);

        $cuenta = User::where('username', '201809372')->first();
        $this->assertNotNull($cuenta);
        $this->assertSame('201809372@est.umss.edu', $cuenta->email);
        $this->assertTrue($cuenta->debe_cambiar_password);
        $this->assertSame('estudiante', $cuenta->rol->nombre_rol);
        $this->assertSame('Ana Perez', $cuenta->name);
        // La contraseña inicial es el documento de identidad: se fuerza el cambio.
        $this->assertTrue(Hash::check('1111111', $cuenta->password));

        // El QR autogenerado corresponde al mismo estudiante.
        $this->assertSame($cuenta->estudiante->codigo_qr, Estudiante::qrPayload('201809372'));
    }

    public function test_update_syncs_account_name_and_email(): void
    {
        $admin = $this->createAdmin();

        $this->actingAs($admin)->post('/estudiantes', [
            'codigo_universitario' => '201809372',
            'documento_identidad' => '1111111',
            'nombres' => 'Ana',
            'apellidos' => 'Perez',
            'email' => '201700001@est.umss.edu',
        ]);

        $estudiante = Estudiante::where('codigo_universitario', '201809372')->first();

        $this->actingAs($admin)->put("/estudiantes/{$estudiante->id_estudiante}", [
            'codigo_universitario' => '201809372',
            'documento_identidad' => '1111111',
            'nombres' => 'Ana Maria',
            'apellidos' => 'Perez Cruz',
            'email' => '202011220@est.umss.edu',
        ])->assertSessionHas('success');

        $this->assertDatabaseHas('estudiante', [
            'codigo_universitario' => '201809372',
            'email' => '202011220@est.umss.edu',
        ]);

        $this->assertDatabaseHas('users', [
            'username' => '201809372',
            'name' => 'Ana Maria Perez Cruz',
            'email' => '202011220@est.umss.edu',
        ]);
    }

    public function test_qr_route_returns_svg_and_backfills_payload(): void
    {
        $admin = $this->createAdmin();
        $estudiante = Estudiante::create([
            'codigo_universitario' => '201809374',
            'documento_identidad' => '3333333',
            'nombres' => 'Luis',
            'apellidos' => 'Zamora',
        ]);

        $response = $this->actingAs($admin)
            ->get(route('estudiantes.qr', $estudiante->id_estudiante));

        $response->assertOk();
        $response->assertHeader('Content-Type', 'image/svg+xml');

        // El payload se genera bajo demanda y queda persistido.
        $this->assertDatabaseHas('estudiante', [
            'id_estudiante' => $estudiante->id_estudiante,
            'codigo_qr' => Estudiante::qrPayload('201809374'),
        ]);
    }
}
